/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;



public class App {

    
    public static void main(String[] args) {

            InputsFromUser.inputFromUser();


    }

}
